[profile.default]
optimizer                 = true
optimizer_runs            = 200
out                       = "out"
libs                      = ["lib"]
ffi                       = false      
fork_url                  = "boojum"
fork_block_number         = 320

[rpc_endpoints]
boojum = "${RPC_URL}"
era = "https://mainnet.era.zksync.io"